// =============================================================================
// Power Query M — PA-TURAMA dbo.OPSView (optimized)
// =============================================================================
// BEFORE USE — Create a Power Query PARAMETER in Excel:
//   Name: LastRefresh
//   Type: Date/Time (datetime)
//   Suggested default: #datetime(2000, 1, 1, 0, 0, 0) for first full load,
//   then update the parameter (or bind to a cell) to the last successful
//   refresh time for incremental-style loads.
//
// Check "View Native Query" on the Filtered step — if SQL shows WHERE
// Booking_Entered_Datetime > @p (or similar), folding works. If not, use
// NativeQuery / DBA view with an explicit WHERE clause.
// =============================================================================

let
    Source = Sql.Databases("PA-TURAMA.data.tourplan.net,50311"),
    DB = Source{[Name="PA-TURAMA"]}[Data],
    OPSView = DB{[Schema="dbo",Item="OPSView"]}[Data],

    // Incremental-style row cut (must fold for real benefit — verify native query)
    Filtered = Table.SelectRows(OPSView, each [Booking_Entered_Datetime] > LastRefresh),

    Typed = Table.TransformColumnTypes(Filtered, {
        {"Booking_Last_Service_Date", type date},
        {"Product_Cost_Inc", Currency.Type},
        {"Booking_Travel_Date", type date},
        {"Pickup_Time", type time},
        {"PICKUP_DATE", type date},
        {"Service_Date", type date},
        {"DROPOFF_DATE", type date},
        {"Booking_Entered_Date", type date},
        {"Booking_Entered_Datetime", type datetime},
        {"Pax", Int64.Type},
        {"Children", Int64.Type},
        {"Infants", Int64.Type},
        {"RoomNights", Int64.Type},
        {"Rooms", Int64.Type},
        {"Singles", Int64.Type},
        {"Twins", Int64.Type},
        {"Doubles", Int64.Type},
        {"Triples", Int64.Type},
        {"Quads", Int64.Type},
        {"Others", Int64.Type},
        {"Nights", Int64.Type},
        {"Voucher_Number", Int64.Type},
        {"FreeNights", Int64.Type},
        {"Escorts", Int64.Type},
        {"Drivers", Int64.Type},
        {"Guides", Int64.Type},
        {"Day_Number", Int64.Type},
        {"Sequence_Number", Int64.Type},
        {"Product_Exchange_Rate", type number},
        {"Product_Retail_Price_Inc", Currency.Type}
    }),

    BookingBranchMap = [
        AC = "AITUTAKI.COM",
        AD = "ADMINISTRATION",
        DC = "DISCOVER COOK ISLANDS",
        DM = "DMCK",
        IC = "ISLAND HOPPER VACATIONS",
        IS = "ISLAND HOPPER VACATION SAMOA",
        RE = "ISLAND HOPPER RETAIL",
        RT = "RARO TOURS",
        TP = "TIPANI TOURS",
        UA = "UNASSIGNED"
    ],
    WithBookingBranch = Table.AddColumn(Typed, "Booking Branch Name", each Record.FieldOrDefault(BookingBranchMap, [Booking_Branch], [Booking_Branch])),
    RemovedBookingBranchCode = Table.RemoveColumns(WithBookingBranch, {"Booking_Branch"}),

    // Chained from RemovedBookingBranchCode (not Typed) so "Booking Branch Name" is kept
    BookingStatusMap = [
        CF = "Confirmed",
        FI = "Fully Invoiced",
        ID = "Deposit Invoiced",
        PR = "Provisional",
        QT = "Quote",
        WB = "Web Confirmed",
        WF = "Web Fully Invoiced",
        WQ = "Web Quote",
        WX = "Web Cancelled",
        XC = "Cancelled with Cost",
        XX = "Cancelled"
    ],
    WithBookingStatus = Table.AddColumn(RemovedBookingBranchCode, "Booking Status", each Record.FieldOrDefault(BookingStatusMap, [Booking_Status], [Booking_Status])),
    RemovedBookingCode = Table.RemoveColumns(WithBookingStatus, {"Booking_Status"}),

    ServiceStatusMap = [
        FS = "Freesell",
        IS = "Initial Status",
        IT = "Itinerary Only",
        KA = "Confirmed Allotment",
        KE = "Confirmed Externally",
        KF = "Confirmed Freesell",
        KK = "Confirmed",
        OP = "Optional",
        PA = "Partial Allotment",
        QE = "Quoted Externally",
        QT = "Quote Only",
        RA = "Amendment Request",
        RQ = "On Request",
        UN = "Unavailable",
        WL = "Waitlisted",
        XC = "Cancel - Charge",
        XE = "Cancelled External",
        XX = "Cancelled"
    ],
    WithServiceStatus = Table.AddColumn(RemovedBookingCode, "Service Status", each Record.FieldOrDefault(ServiceStatusMap, [Service_Status], "Unassigned")),

    RenamedColumns = Table.RenameColumns(WithServiceStatus, {
        {"Product_Cost_Inc", "Cost"},
        {"Product_Retail_Price_Inc", "Sales"},
        {"Service_Margin_Inc", "Margin"},
        {"Pickup", "Pickup Location"},
        {"Dropoff", "Dropoff Location"},
        {"Booking_Consultant", "Booking Consultant Code"},
        {"Booking_Consultant_Name", "Booking Consultant Name"},
        {"Agent_MailAddress5", "Agent Country"},
        {"Agent_Name", "Agent Name"},
        {"Agent_Analysis2_Name", "Agent Region"},
        {"Agent_Analysis4_Name", "Agent Mark Up"},
        {"Agent_Analysis1_Name", "Agent Type"},
        {"Supplier_Analysis4_Name", "Supplier Account Type"},
        {"Booking_Text1", "Flight Arrival"},
        {"Booking_Text3", "Flight Departure"},
        {"Booking_Analysis1_Name", "Booking Type"}
    }),

    ColumnsToRemove = {
        "Booking_Analysis1",
        "Supplier_PhysicalAddress1",
        "Supplier_PhysicalAddress2",
        "Supplier_PhysicalAddress3",
        "Supplier_PhysicalAddress4",
        "Supplier_PhysicalAddress5",
        "Supplier_PhysicalPostcode",
        "Supplier_MailAddress1",
        "Supplier_MailAddress2",
        "Supplier_MailAddress3",
        "Supplier_MailAddress4",
        "Supplier_MailAddress5",
        "Supplier_MailPostcode",
        "Agent_PhysicalAddress1",
        "Agent_PhysicalAddress2",
        "Agent_PhysicalAddress3",
        "Agent_PhysicalAddress4",
        "Agent_PhysicalAddress5",
        "Agent_PhysicalPostcode",
        "Agent_MailAddress1",
        "Agent_MailAddress2",
        "Agent_MailAddress3",
        "Agent_MailAddress4",
        "Agent_MailPostcode",
        "Rate_Voucher_Text1",
        "Rate_Voucher_Text2",
        "Rate_Voucher_Text3",
        "Rate_Voucher_Text10",
        "Product_Destination",
        "Product_Destination_Name",
        "Booking_Analysis5",
        "Booking_Analysis5_Name",
        "Supplier_Analysis2",
        "Supplier_Analysis2_Name",
        "Agent_Analysis4",
        "Supplier_Analysis1",
        "Supplier_Analysis4",
        "Supplier_Chain",
        "Agent_Chain",
        "Product_PriceCode",
        "Pickup_Time",
        "Dropoff_Time",
        "Voucher_Text1",
        "Voucher_Text2",
        "Retail_Price_Inc",
        "Agent_Price",
        "Product_Cost",
        "Retail_Price",
        "Service_Cost",
        "Service_Cost_Inc",
        "Service_Margin",
        "Product_Margin",
        "Product_Margin_Inc",
        "Agent_Price_Inc",
        "Product_Agent_Price",
        "Product_Agent_Price_Inc",
        "Product_Retail_Price",
        "Voucher_Text3",
        "Voucher_Text4",
        "Voucher_Text5",
        "Voucher_Text6",
        "Voucher_Text7",
        "Voucher_Text8",
        "Voucher_Text9",
        "Voucher_Text10",
        "Service_Commission",
        "Service_Commission_Inc",
        "Product_Commission",
        "Product_Commission_Inc",
        "Booking_Analysis6",
        "Booking_Analysis6_Name",
        "Agent_Analysis3_Name",
        "Agent_Analysis5",
        "Agent_Analysis5_Name",
        "Agent_Analysis6",
        "Agent_Analysis6_Name",
        "Supplier_Analysis3",
        "Supplier_Analysis3_Name",
        "Supplier_Analysis5",
        "Supplier_Analysis5_Name",
        "Supplier_Analysis6",
        "Supplier_Analysis6_Name",
        "Product_Analysis2",
        "Product_Analysis2_Name",
        "Product_Analysis3",
        "Product_Analysis3_Name",
        "Product_Analysis4",
        "Product_Analysis4_Name",
        "Product_Analysis5",
        "Product_Analysis5_Name",
        "Product_Analysis6",
        "Product_Analysis6_Name",
        "Airline_Code",
        "Plate_Number",
        "Agent_Text2",
        "Agent_Text3",
        "Agent_Text4",
        "Agent_Text5",
        "Supplier_Text1",
        "Supplier_Text2",
        "Supplier_Text3",
        "Supplier_Text4",
        "Supplier_Text5",
        "Product_Locality",
        "Product_Locality_Description",
        "Rate_Voucher_Text4",
        "Rate_Voucher_Text5",
        "Rate_Voucher_Text6",
        "Rate_Voucher_Text7",
        "Rate_Voucher_Text8",
        "Rate_Voucher_Text9"
    },
    Cleaned = Table.RemoveColumns(RenamedColumns, ColumnsToRemove, MissingField.Ignore),

    Adults = Table.AddColumn(Cleaned, "Adults", each [Pax] - [Children] - [Infants]),

    // Backtick cleanup on flight columns (after rename)
    ReplacedBackticks = Table.ReplaceValue(Adults, "`", "", Replacer.ReplaceText, {"Flight Arrival", "Flight Departure"}),

    // Text columns: empty string and null -> "no data present"
    ColumnTypes = Table.Schema(ReplacedBackticks),
    TextColumns = List.Select(ColumnTypes[Name], each ColumnTypes{[Name = _]}[Kind] = "text"),
    ReplaceBlanks = Table.ReplaceValue(ReplacedBackticks, "", "no data present", Replacer.ReplaceText, TextColumns),
    ReplaceNulls = Table.ReplaceValue(ReplaceBlanks, null, "no data present", Replacer.ReplaceValue, TextColumns),

    Reordered = Table.ReorderColumns(ReplaceNulls, {
        "Booking_Travel_Date",
        "Pax",
        "Adults",
        "Children",
        "Booking_Name",
        "Booking_Reference",
        "Booking Status",
        "Supplier_Name",
        "Cost",
        "Sales",
        "Margin",
        "Infants",
        "Booking Branch Name",
        "Agent Name",
        "Booking_Entered_Date",
        "Service_Date",
        "Booking_Department_Name",
        "Supplier_Code",
        "Remarks",
        "RoomNights",
        "Service Status",
        "Agent_Code",
        "Agent Country",
        "Product_Location",
        "Product_Option_Name",
        "Agent_Reference",
        "Booking_Entered_Datetime",
        "Pickup Location",
        "Dropoff Location",
        "Rooms",
        "Singles",
        "Twins",
        "Doubles",
        "Triples",
        "Quads",
        "Others",
        "Nights",
        "Booking Consultant Name",
        "Agent_Analysis2",
        "Product_Service_Name",
        "Product_Option",
        "supplier_confirmation",
        "Voucher_Number",
        "VOUCHER_STATUS",
        "Booking Consultant Code",
        "Booking_Analysis3_Name",
        "Booking_Analysis4_Name",
        "Agent_Analysis1",
        "Agent Mark Up",
        "Supplier_Currency",
        "Product_Service",
        "Product_Analysis1",
        "Product_Analysis1_Name",
        "Agent_Chain_Name",
        "FreeNights",
        "Escorts",
        "Drivers",
        "Guides",
        "Day_Number",
        "Product_Country",
        "Service_Source",
        "Booking_Last_Service_Date",
        "Booking_Currency",
        "Agent Type",
        "Agent Region",
        "Supplier Account Type",
        "Product_Country_Name",
        "Booking Type",
        "Booking_Analysis2",
        "Booking_Analysis2_Name",
        "Booking_Analysis3",
        "Booking_Analysis4",
        "Agent_Currency",
        "Supplier_Analysis1_Name",
        "Product_Location_Name",
        "Supplier_Chain_Name",
        "Agent_Text1",
        "Flight Arrival",
        "Booking_Text2",
        "Flight Departure",
        "Booking_Text4",
        "Booking_Text5",
        "Product_Class",
        "Product_Class_Description",
        "Product_Exchange_Rate",
        "Product_Option_Comment",
        "Product_PriceCode_Name",
        "Sequence_Number",
        "Service_Cost_Currency",
        "Service_Sell_Currency",
        "PICKUP_DATE",
        "DROPOFF_DATE"
    }),
    #"Changed Type" = Table.TransformColumnTypes(Reordered, {{"Margin", Currency.Type}})
in
    #"Changed Type"
